386_OBJECTS= \
    $(_OBJ_DIR)\i386\passthru.res \
    $(_OBJ_DIR)\i386\miniport.obj \
    $(_OBJ_DIR)\i386\passthru.obj \
    $(_OBJ_DIR)\i386\protocol.obj \
    $(_OBJ_DIR)\i386\ptextend.obj \
    $(_OBJ_DIR)\i386\filter.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\passthru.res \
    $(_OBJ_DIR)\ia64\miniport.obj \
    $(_OBJ_DIR)\ia64\passthru.obj \
    $(_OBJ_DIR)\ia64\protocol.obj \
    $(_OBJ_DIR)\ia64\ptextend.obj \
    $(_OBJ_DIR)\ia64\filter.obj

PASS0_IA64_OBJECTS=

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\passthru.res \
    $(_OBJ_DIR)\amd64\miniport.obj \
    $(_OBJ_DIR)\amd64\passthru.obj \
    $(_OBJ_DIR)\amd64\protocol.obj \
    $(_OBJ_DIR)\amd64\ptextend.obj \
    $(_OBJ_DIR)\amd64\filter.obj

PASS0_AMD64_OBJECTS=

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\passthru.res \
    $(_OBJ_DIR)\arm\miniport.obj \
    $(_OBJ_DIR)\arm\passthru.obj \
    $(_OBJ_DIR)\arm\protocol.obj \
    $(_OBJ_DIR)\arm\ptextend.obj \
    $(_OBJ_DIR)\arm\filter.obj

PASS0_ARM_OBJECTS=

